import json
import os
from config.settings import supabase, SERP_KEY, gemini, model
from google.genai import types
from serpapi import GoogleSearch

COUNTRY_MAP = {
    "india": "in",
    "united states": "us",
    "usa": "us",
    "united kingdom": "uk", 
    "canada": "ca",
    "australia": "au",
    "germany": "de",
    "france": "fr",
    "japan": "jp"
}

def get_location_codes(user_location):
    """
    Extracts the country from the location string and returns the gl and hl codes.
    """
    country_name = user_location.split(",")[-1].strip().lower()
    
    gl_code = COUNTRY_MAP.get(country_name, "us")
    
    hl_code = "en" 
    
    return gl_code, hl_code


def check_cache(gemini_response, user_location):
    """
    Checks the Supabase cache for a matching product in the same city.
    """
    product_name = gemini_response.get("product_name", "").lower()
    brand = gemini_response.get("brand", "").lower()
    
    city = user_location.split(",")[0].strip()
    
    print(f"Checking cache for: {brand} {product_name} in {city}...")
    
    try:
        response = supabase.table('cached_products') \
            .select('*') \
            .ilike('city', city) \
            .ilike('brand', brand) \
            .ilike('product_name', product_name) \
            .execute()
            
        if response.data and len(response.data) > 0:
            hit = response.data[0]
            if hit.get("domestic_price"):
                print("Cache hit found (with domestic price)!")
                return hit
            print("Cache hit found but no domestic price — skipping.")
        
        print("No cache hit.")
        return None
    
    except Exception as e:
        print("Error checking cache:", e)
        return None

def check_serp(gemini_response, user_location):
    """
    Checks Google Shopping via SerpAPI for market prices.
    Uses the search_query generated by Gemini for better results.
    Falls back to brand + product_name if search_query is missing.
    Tries a broader second search if the first returns nothing.
    """
    search_query = gemini_response.get("search_query", "").strip()
    if not search_query:
        brand = gemini_response.get("brand", "")
        product_name = gemini_response.get("product_name", "")
        category = gemini_response.get("category_serpapi", "")
        search_query = f"{brand} {product_name} {category}".strip()

    gl_code, hl_code = get_location_codes(user_location)

    # Build a broader fallback query (just brand + product_name)
    brand = gemini_response.get("brand", "")
    product_name = gemini_response.get("product_name", "")
    broad_query = f"{brand} {product_name}".strip()

    for attempt, q in enumerate([search_query, broad_query], 1):
        if not q:
            continue

        print(f"🔍 SerpAPI attempt {attempt}: '{q}' (gl={gl_code})")

        params = {
            "engine": "google_shopping",
            "q": q,
            "hl": hl_code,
            "gl": gl_code,
            "api_key": SERP_KEY
        }

        try:
            search = GoogleSearch(params)
            results = search.get_dict()
            shopping_results = results.get("shopping_results", [])
            print(f"🔍 SerpAPI returned {len(shopping_results)} results")
            if shopping_results:
                return shopping_results
        except Exception as e:
            print(f"SerpAPI error: {e}")

    print("🔍 SerpAPI: no results after all attempts")
    return []

def check_numbeo(gemini_response, user_location):
    """
    Checks Numbeo for cost of living data based on the user's location.
    """
    product_category = gemini_response.get("category_numbeo_csv")
    city = user_location.split(",")[0].strip()

    if not product_category:
        print("No Numbeo category mapped. Skipping cost-of-living check.")
        return None
        
    if not city:
        print("Missing city for Numbeo check.")
        return None

    print(f"Fetching local cost for '{product_category}' in {city}...")

    try:
        response = supabase.table('numbeo_scrape') \
            .select(product_category) \
            .ilike('city', city) \
            .execute()
            
        if len(response.data) > 0:
            local_cost = response.data[0].get(product_category)
            print(f"Numbeo Baseline Cost: ${local_cost}")
            return local_cost
        else:
            print("No Numbeo data found for this city.")
            return None
            
    except Exception as e:
        print("Error fetching Numbeo data:", e)
        return None

def check_gemini_scanned_price(gemini_response, user_location):
    """
    Estimates the SCANNED / SHELF price when Gemini vision couldn't read it from the image.
    This is NOT the market price — it's what the product likely costs at the store.
    """
    product_name = gemini_response.get("product_name")
    brand = gemini_response.get("brand", "")

    if not product_name:
        print("Missing product name for Gemini price estimate.")
        return None

    print(f"💡 No price visible in image. Asking Gemini to estimate shelf price for {brand} {product_name} in {user_location}...")

    prompt_path = os.path.join(os.path.dirname(__file__), 'failover_prompt.json')
    with open(prompt_path, 'r') as f:
        prompts = json.load(f)

    system_prompt = prompts["system_prompt"].format(
        brand=brand,
        product_name=product_name,
        user_location=user_location
    )

    expected_format = json.dumps(prompts["expected_format"], indent=2)
    failover_prompt = f"{system_prompt}\n\nReturn ONLY a valid JSON object with no markdown formatting:\n{expected_format}"

    try:
        response = gemini.models.generate_content(
            model=model,
            contents=failover_prompt,
            config=types.GenerateContentConfig(
                temperature=0.2,
                response_mime_type="application/json",
            )
        )

        estimated_data = json.loads(response.text)
        price = estimated_data.get('estimated_price')
        print(f"💡 Gemini Shelf Estimate: {price} {estimated_data.get('currency')} (Confidence: {estimated_data.get('confidence')})")
        return price

    except Exception as e:
        print("Error during Gemini price estimate:", e)
        return None
    
def add_to_cache(gemini_response, user_location, product_price, domestic_price=None, store_name=None, is_pink_tax=False):
    """
    Adds a new entry to the cache in Supabase.
    Only inserts when domestic_price is present and no duplicate exists
    (same product_name, brand, city, domestic_price).
    """
    if not domestic_price:
        print("No domestic price — skipping cache insert.")
        return

    product_name = gemini_response.get("product_name", "Unknown")
    brand = gemini_response.get("brand", "Unknown")

    location_parts = [part.strip() for part in user_location.split(",")]
    city = location_parts[0] if len(location_parts) > 0 else "Unknown"
    country = location_parts[-1] if len(location_parts) > 1 else "Unknown"

    # ── Duplicate check ──────────────────────────────────────────────
    try:
        existing = supabase.table('cached_products') \
            .select('id') \
            .ilike('product_name', product_name) \
            .ilike('brand', brand) \
            .ilike('city', city) \
            .eq('domestic_price', domestic_price) \
            .limit(1) \
            .execute()

        if existing.data and len(existing.data) > 0:
            print(f"Duplicate already cached for {brand} {product_name} in {city} — skipping.")
            return
    except Exception as e:
        print("Error during duplicate check:", e)

    volume = gemini_response.get("volume", "")
    category = gemini_response.get("category_serpapi", "")
    product_des = f"{volume} - {category}".strip(" -")

    payload = {
        "product_name": product_name,
        "product_price": product_price,
        "product_des": product_des if product_des else None,
        "pink_tax": is_pink_tax,
        "store_name": store_name,
        "city": city,
        "country": country,
        "domestic_price": domestic_price,
        "brand": brand
    }

    try:
        supabase.table('cached_products').insert(payload).execute()
        print("Successfully added entry to cached_products.")
    except Exception as e:
        print("Error adding to cache:", e)
        
def run_equispend_analysis(gemini_vision_json, user_location):
    """
    MASTER ORCHESTRATOR: Runs the Equispend Waterfall Logic Flow.

    Scanned price = what Gemini sees in the image (or estimates if not visible).
    Market price  = what SERP / Numbeo says it should cost.
    """
    print(f"\n🚀 Starting Equispend Analysis for {user_location}...")

    # ── Step 1: Determine scanned price ──────────────────────────────
    scanned_price = gemini_vision_json.get("price_found")

    if not scanned_price:
        # No price visible in the image → ask Gemini to estimate the shelf price
        estimated = check_gemini_scanned_price(gemini_vision_json, user_location)
        if estimated:
            scanned_price = estimated
            gemini_vision_json["price_found"] = estimated   # keep in sync
            print(f"📌 Using Gemini estimated shelf price: {scanned_price}")
        else:
            print("⚠️ Could not determine scanned price at all.")

    # ── Step 2: Check cache ──────────────────────────────────────────
    cached_data = check_cache(gemini_vision_json, user_location)
    if cached_data:
        return {
            "status": "success",
            "source": "supabase_cache",
            "data": cached_data
        }

    # ── Step 3: Find market price via SERP ───────────────────────────
    print("🌐 Searching for market price...")
    market_price = None
    store_name = None

    shopping_results = check_serp(gemini_vision_json, user_location)

    if shopping_results and len(shopping_results) > 0:
        market_price = shopping_results[0].get("extracted_price")
        store_name = shopping_results[0].get("source")
        print(f"✅ SerpAPI market price: ${market_price} at {store_name}")

    # ── Step 4: Numbeo fallback for market baseline ──────────────────
    local_cost = check_numbeo(gemini_vision_json, user_location)

    if not market_price and local_cost:
        market_price = local_cost
        store_name = "Numbeo Cost-of-Living"
        print(f"📊 Using Numbeo baseline as market price: ${market_price}")

    # ── Step 5: Determine markup ─────────────────────────────────────
    is_pink_tax = False
    if scanned_price and market_price:
        if float(scanned_price) > float(market_price):
            is_pink_tax = True

    # ── Step 6: Cache the result (only when both prices are known) ───
    if scanned_price and market_price:
        add_to_cache(
            gemini_response=gemini_vision_json,
            user_location=user_location,
            product_price=scanned_price,
            domestic_price=market_price,
            store_name=store_name,
            is_pink_tax=is_pink_tax
        )
    else:
        print("⚠️ Missing scanned or market price. Skipping cache insert.")

    return {
        "status": "success",
        "source": "live_pipeline",
        "data": {
            "scanned_price": scanned_price,
            "domestic_market_price": market_price,
            "numbeo_local_cost": local_cost,
            "is_pink_tax": is_pink_tax,
            "store_match": store_name
        }
    }